### ISSUE TITLE
Media Gallery shows in wrong place in Moodle 3

### ISSUE THREAD

**Issue by stopfstedt** [kaltura/moodle_plugin#137] opened 2017-05-15 17:29 UTC
_originally filed here kaltura/moodle-local_kalturamediagallery#1_

Hi,
We're in the process of upgrading to Moodle 3.2 and noticed that the Media Gallery appears in the now-defunct "Current Course" section of the navigation block (we're using a Clean-theme based custom theme, and intend to do so for the foreseeable future).

![selection_254](https://cloud.githubusercontent.com/assets/1410427/26070412/6646792c-3959-11e7-9a0e-e59cf904bc76.png)

Instead the link should appear underneath with the currently active course within the "My courses" or "Courses" sections:

![selection_253](https://cloud.githubusercontent.com/assets/1410427/26070417/69a5703c-3959-11e7-9f6f-7e0a2a070752.png)

![selection_252](https://cloud.githubusercontent.com/assets/1410427/26070517/d38639e6-3959-11e7-8a9c-d3873873bdc9.png)

**Comment by kaltura-hooks** [comment] 2017-05-15 17:34
Hi @stopfstedt,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by cdipe** [comment] 2017-05-16 07:50
Actually, the problem is (according to Gavin Henrick at Moodle.org) that the Kaltura plugin is causing "Participants", "Grades" and the other stuff that should be under Current Course, to end up in the wrong place.
It's reported in moodle tracker here: https://tracker.moodle.org/browse/MDL-58213

I have also reported this to Kaltura (Case# 00135736) and got the answer 21st of April: 

"Hello Peter,
Thank you for contacting Kaltura Customer Care.
Reviewing the submitted case, I am able to reproduce this matter on our test Moodle environment. (version 3.2).
Therefore, kindly note I have escalated this matter to our Product team for further investigation.
Rest assured I will update you as soon as new information is available to share.
Regards,
Omer H. | Kaltura Customer Care | Kaltura Inc."

**Comment by muli** [comment] 2017-05-16 08:56
Hi @cdipe,

Thanks for this important comment.

It seems that we at Kaltura weren't aware of the negative impact of Moodle's change to the navigation block (i.e. the removal of "current course" node) to customers, and as such, our initial plan was to tag along Moodle's change and "fix" our plugin to comply with it.

However, after reading MDL-58213, it seems like this plan should change.
I will consult with our product team and I will update you as soon as possible.

@idodido, @gonenradai - FYI.

**Comment by cdipe** [comment] 2017-05-16 08:58
Thank you!

**Comment by stopfstedt** [comment] 2017-05-18 17:35
**UPDATE** The patch submitted [here](https://tracker.moodle.org/browse/MDL-58213?focusedCommentId=466128&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-466128) would make this issue irrelevant.

**Closed as completed** 2017-05-19 16:54 UTC
